### ISSUE TITLE
How to install and setup documentation needed

### ISSUE THREAD

**Issue by chromonav** [dhirenrouterabbit/ionic-community#1]
Documentation regarding installation and seting up project is needed which should contain:
1.Recommended Node version
2.External Dependencies
3.How to configure system resources

**Comment by bytesofdhiren** [comment]
For ubuntu
1. Node version - 4. Install by 
    curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
    sudo apt-get install -y nodejs
2. External dependencies
    http://ionicframework.com/getting-started/
3. System resource - What you mean by system resources?
